name: cf_ta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  get: ^4.7.3
  google_fonts: 6.3.2
  flutter_animate: ^4.5.2
  iconsax: ^0.0.8
  animated_bottom_navigation_bar: ^1.4.0
  intl: ^0.20.2
  http: ^1.6.0
  firebase_database: ^12.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
